### ISSUE TITLE
serv_offer多图片功能（一）

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#16]
判断为this.state.avatarSource === undefined显示一个缺省的图片；
加一个数据用来保存多个图片的地址；
多图片用分隔符“,”拼装保存到serv_images里。

**Comment by loveImanity** [comment]
[提交代码版本](https://github.com/sguo2017/Tispr/commit/5776b4baea5b02e63b88f58ac45aa96af129c385)
