### ISSUE TITLE
用户信息缓存

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#18]

**Comment by sguo2017** [comment]
之前你处理过的

**Comment by sguo2017** [comment]
关闭掉

**Comment by loveImanity** [comment]
[提交代码1](https://github.com/sguo2017/Tispr/commit/4362edcfede16d1037f4b97c31f6ed17ddba159e)
[提交代码2](https://github.com/sguo2017/Tispr/commit/8d47d5b502cf3259b2180dc8cbbe0f4cfa80310d)
