### ISSUE TITLE
判断是否被收藏标示"isFavorited":false

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#42]
sys_msg_list数据列子：

    {
        "id":64,
        "user_name":"Jim",
        "action_title":"created an offer",
        "action_desc":"p0 测试123456",
        "user_id":5,
        "created_at":"2017-04-16T07:59:45.000Z",
        "updated_at":"2017-04-16T07:59:45.000Z",
        "serv_id":76,
        "serv_offer":{
            "id":76,
            "serv_title":"p0 测试123456",
            "serv_detail":"p0测试 独孤皇后回个话哈郭v宝贝还回家 ",
            "serv_imges":"http://123.56.157.233:8080/group1/M00/00/02/ezid6VjzJG-Af8YSAABXJBQphGc151.jpg",
            "serv_catagory":null,
            "created_at":"2017-04-16T07:59:45.000Z",
            "updated_at":"2017-04-16T07:59:45.000Z",
            "user_id":5
        },
        "user":{
            "id":5,
            "email":"p0@qq.com",
            "created_at":"2017-04-04T05:44:45.000Z",
            "updated_at":"2017-04-20T09:15:27.000Z",
            "authentication_token":"***",
            "name":"Jim",
            "avatar":"http://123.56.157.233:8080/group1/M00/00/02/ezid6VjwkI2Ac0HlAAAWC87n9H4436.jpg",
            "admin":false
        },
        "isFavorited":false

**Comment by zengkm** [comment]
[代码版本号](https://github.com/sguo2017/Tispr/commit/82c9b50e09fdf9f37cbbcf62680f4e88d323d072)
