### ISSUE TITLE
订单流转：第二步：询价期：买卖双方都可以报价

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#44]

**Comment by sguo2017** [comment]
API:curl -X PATCH -H "Content-Type: application/json" -d '{"order":{"status":"00B"}}' localhost:3000/api/order/orders/33.json?token=puB8hFbBySpx-9GKUF3Y

**Comment by zengkm** [comment]
不能向自己询价

**Comment by zengkm** [comment]
[代码版本号](https://github.com/sguo2017/Tispr/commit/89d49c92f11c0542161150c4ac3132168c61054d)
