### ISSUE TITLE
订单流转：第三步：有人报价

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#45]

**Comment by sguo2017** [comment]
API:curl -X PATCH -H "Content-Type: application/json" -d '{"order":{"status":"00B"}}' localhost:3000/api/order/orders/33.json?token=puB8hFbBySpx-9GKUF3Y

**Comment by zengkm** [comment]
[代码版本号](https://github.com/sguo2017/Tispr/commit/644c8897716f6e37d7b30167733b940b278f9eda)
