### ISSUE TITLE
订单流转：第四步：其他人确认

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#46]
API:curl -X PATCH -H "Content-Type: application/json" -d '{"order":{"status":"00B"}}' localhost:3000/api/order/orders/33.json?token=puB8hFbBySpx-9GKUF3Y

**Comment by zengkm** [comment]
[代码版本号](https://github.com/sguo2017/Tispr/commit/1a52cf34f4cc983cdd0bbf81ba1356f553c89cd9)
