### ISSUE TITLE
将服务端的ip和端口常量化

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#6]
1、定义服务端ip常量、端口常量；
2、修改登录调用服务端的URL；
3、修改serv_offer的confrim提交URL；

**Comment by loveImanity** [comment]
提交代码https://github.com/sguo2017/Tispr/commit/416f612d2ad0debc3777691a1d94ef0dd2e962d1

**Comment by loveImanity** [comment]
提交代码[版本号](https://github.com/sguo2017/Tispr/commit/416f612d2ad0debc3777691a1d94ef0dd2e962d1)
