### ISSUE TITLE
缓存goods_catalogs数据

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#72]
1、初始化：在“explore”或“+”区展现时，第一次从后端读取数据，读取后缓存到全局对象中；
2、使用：再次“explore”或“+”区展现时，从全局变量中读取；

**Comment by loveImanity** [comment]
提交代码[版本](https://github.com/sguo2017/Tispr/commit/1dade4dfae8277d41a7966257f74d0688d59b4cb)
