### ISSUE TITLE
【动态】样式优化

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#87]
1、缺少“奇客动态”；
2、列表样式见UI，进行调整下；
3、增加“正在掌控”卡片：排在第一是“左右滑动说明”；排在“第二”是“正在滑动”卡片；排在“第三”是“轻松开始”卡片；
4、你有“重要更新”样式调整；

**Comment by Kariko** [comment]
完成1，2，4[代码版本](https://github.com/sguo2017/Tispr/commit/6108607d319923c93e961061ac99f6bdc533b950)
