### ISSUE TITLE
【我的】主页优化

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/Tispr#90]
同UI一致

**Comment by Kariko** [comment]
[代码版本](https://github.com/sguo2017/Tispr/commit/cb5abaeaf08727fa3416aa98aba558af391cc58c)

**Comment by Kariko** [comment]
[代码版本](https://github.com/sguo2017/Tispr/commit/3c19beeef2cda2057f781e54460a44e5e0e2789c)
